name: riscv64

on:
  push:
    branches:
      - riscv-tests
    tags:
      - ciflow/riscv64/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

permissions: read-all

jobs:
  pytorch-linux-noble-riscv64-py3_12-gcc14-cross-build:
    name: pytorch-linux-noble-riscv64-py3.12-gcc14-cross-build
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-noble-riscv64-py3.12-gcc14
      docker-image-name: pytorch-linux-noble-riscv64-py3.12-gcc14
      runner: linux.c7i.2xlarge
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 3, runner: "RISCV64" },
          { config: "default", shard: 2, num_shards: 3, runner: "RISCV64" },
          { config: "default", shard: 3, num_shards: 3, runner: "RISCV64" },
          { config: "openreg", shard: 1, num_shards: 1, runner: "RISCV64" },
        ]}
    secrets: inherit

  pytorch-linux-noble-riscv64-py3_12-gcc14-test:
    name: pytorch-linux-noble-riscv64-py3.12-gcc14-test
    uses: ./.github/workflows/_linux-test.yml
    needs: pytorch-linux-noble-riscv64-py3_12-gcc14-cross-build
    permissions:
      id-token: write
      contents: read
    with:
      build-environment: ${{ needs.pytorch-linux-noble-riscv64-py3_12-gcc14-cross-build.outputs.build-environment }}
      docker-image: ${{ needs.pytorch-linux-noble-riscv64-py3_12-gcc14-cross-build.outputs.docker-image }}
      test-matrix: ${{ needs.pytorch-linux-noble-riscv64-py3_12-gcc14-cross-build.outputs.test-matrix }}
      timeout-minutes: 720
    secrets: inherit
